// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1uJzL_n5kASiR6fDbxysOYhGvWF4Cf_Y',
    appId: '1:113891078966:web:e40214fadfeb39b5823997',
    messagingSenderId: '113891078966',
    projectId: 'control-horario-rega',
    authDomain: 'control-horario-rega.firebaseapp.com',
    storageBucket: 'control-horario-rega.firebasestorage.app',
    measurementId: 'G-PP3NYLTSQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtG8gEmH8kd4890HBFBUk2XgQr-7lFySo',
    appId: '1:113891078966:android:5e7379e3021e71f1823997',
    messagingSenderId: '113891078966',
    projectId: 'control-horario-rega',
    storageBucket: 'control-horario-rega.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0TGrBOJHZwjBBOgR912UBIgkYyMB4XBE',
    appId: '1:113891078966:ios:ec844c6e55b1559c823997',
    messagingSenderId: '113891078966',
    projectId: 'control-horario-rega',
    storageBucket: 'control-horario-rega.firebasestorage.app',
    iosBundleId: 'app.controlhorario.controlHorario',
  );
}
