/**
 * P1a1 — Frozen canonical fixture vectors (ordinal 25 remediation).
 *
 * All expected values are LITERAL independent precomputed constants,
 * NOT generated by production code under test. Integrity checks verify
 * that production functions produce the SAME values as these literals.
 *
 * Every exported value is deep-frozen — suitable for P1a2 handoff.
 */

import {
  type ProvisioningStatus,
  type ProvisioningPhase,
  type StatusPhasePair,
  VALID_STATUS_PHASE_PAIRS,
  isValidStatusPhasePair,
} from "../../src/provisioning/types.ts";

import {
  normalizePayload,
  fingerprintPayload,
  deriveDisplayName,
  type NormalizedPayload,
} from "../../src/provisioning/normalize.ts";

import {
  deriveDispatchId,
  deriveAuditEventId,
  deriveOwnerToken,
} from "../../src/provisioning/ids.ts";

// =========================================================================
// Literal vocabulary fixtures
// =========================================================================

export const CANONICAL_VALID_PAIRS: readonly StatusPhasePair[] = Object.freeze([
  Object.freeze({ status: "pending" as const, phase: "dispatch_pending" as const }),
  Object.freeze({ status: "active" as const, phase: "auth_preflight" as const }),
  Object.freeze({ status: "active" as const, phase: "auth_create" as const }),
  Object.freeze({ status: "active" as const, phase: "profile_commit" as const }),
  Object.freeze({ status: "completed" as const, phase: "terminal" as const }),
  Object.freeze({ status: "failed" as const, phase: "terminal" as const }),
  Object.freeze({ status: "manual_recovery" as const, phase: "terminal" as const }),
]);

/**
 * The accepted P1a2 transition paths, expressed as literal input/output
 * vectors. Adapter conformance consumes this ledger; it must not recreate
 * selected reducer paths in a persistence test.
 */
export interface CanonicalP1aTransitionVector {
  readonly steps: readonly {
    readonly observedAt: number;
    readonly event: Readonly<{
      type: string;
      payload: Readonly<Record<string, unknown>>;
    }>;
    readonly expected: StatusPhasePair;
  }[];
}

const VECTOR_OWNER = "b".repeat(64);
const VECTOR_TAKEOVER_OWNER = "d".repeat(64);
const VECTOR_ATTEMPT = "c".repeat(64);

function transitionStep(
  observedAt: number,
  type: string,
  payload: Record<string, unknown>,
  expected: StatusPhasePair,
): CanonicalP1aTransitionVector["steps"][number] {
  return Object.freeze({
    observedAt,
    event: Object.freeze({
      type,
      payload: Object.freeze(payload),
    }),
    expected: Object.freeze(expected),
  });
}

export const CANONICAL_P1A_TRANSITION_VECTOR_LEDGER: readonly CanonicalP1aTransitionVector[] = Object.freeze([
  Object.freeze({
    steps: Object.freeze([
      transitionStep(1, "acquire", { ownerToken: VECTOR_OWNER, leaseExpiresAt: 10 }, { status: "active", phase: "auth_preflight" }),
      transitionStep(2, "auth_intent", { attemptId: VECTOR_ATTEMPT, intentAt: 2 }, { status: "active", phase: "auth_create" }),
      transitionStep(3, "auth_start", { attemptId: VECTOR_ATTEMPT, callStartedAt: 3 }, { status: "active", phase: "auth_create" }),
      transitionStep(4, "auth_confirm", {
        attemptId: VECTOR_ATTEMPT,
        returnedUid: "uid-1",
        returnedEmail: "employee@example.com",
        proof: Object.freeze({ attemptId: VECTOR_ATTEMPT, confirmedAt: 4, uidRead: "uid-1", emailRead: "employee@example.com" }),
      }, { status: "active", phase: "profile_commit" }),
      transitionStep(5, "profile_commit", { userId: "uid-1" }, { status: "completed", phase: "terminal" }),
    ]),
  }),
  Object.freeze({
    steps: Object.freeze([
      transitionStep(0, "acquire", { ownerToken: VECTOR_OWNER, leaseExpiresAt: 1 }, { status: "active", phase: "auth_preflight" }),
      transitionStep(2, "takeover", { ownerToken: VECTOR_TAKEOVER_OWNER, leaseExpiresAt: 10 }, { status: "active", phase: "auth_preflight" }),
    ]),
  }),
  Object.freeze({
    steps: Object.freeze([
      transitionStep(1, "acquire", { ownerToken: VECTOR_OWNER, leaseExpiresAt: 10 }, { status: "active", phase: "auth_preflight" }),
      transitionStep(2, "auth_intent", { attemptId: VECTOR_ATTEMPT, intentAt: 2 }, { status: "active", phase: "auth_create" }),
      transitionStep(3, "auth_start", { attemptId: VECTOR_ATTEMPT, callStartedAt: 3 }, { status: "active", phase: "auth_create" }),
      transitionStep(4, "auth_ambiguous", { attemptId: VECTOR_ATTEMPT, code: "internal" }, { status: "manual_recovery", phase: "terminal" }),
    ]),
  }),
  Object.freeze({
    steps: Object.freeze([
      transitionStep(1, "acquire", { ownerToken: VECTOR_OWNER, leaseExpiresAt: 10 }, { status: "active", phase: "auth_preflight" }),
      transitionStep(2, "auth_foreign_user", { uid: "foreign", email: "foreign@example.com" }, { status: "failed", phase: "terminal" }),
    ]),
  }),
]);

export const TERMINAL_STATUSES: readonly ProvisioningStatus[] = Object.freeze([
  "completed", "failed", "manual_recovery",
]);

export const NON_TERMINAL_STATUSES: readonly ProvisioningStatus[] = Object.freeze([
  "pending", "active",
]);

// =========================================================================
// Literal sample payloads (raw input)
// =========================================================================

export const SAMPLE_MINIMAL_PAYLOAD: Readonly<Record<string, unknown>> = Object.freeze({
  operationId: "00000000-0000-4000-a000-000000000001",
  email: "juan.perez@example.com",
  nombre: "Juan",
  apellido1: "Pérez",
  role: "employee",
});

export const SAMPLE_FULL_PAYLOAD: Readonly<Record<string, unknown>> = Object.freeze({
  operationId: "00000000-0000-4000-a000-000000000002",
  email: "maria.garcia@example.com",
  nombre: "María",
  apellido1: "García",
  apellido2: "López",
  employeeId: "EMP-001",
  weeklyHours: 35,
  dni: "12345678A",
  telefono: "+34123456789",
  cargo: "Developer",
  departamento: "Engineering",
  empresa: "Test Corp",
  scheduleId: "schedule-001",
  calendarId: "calendar-001",
  fechaInicio: "2025-03-01",
  fechaFin: "2025-12-31",
  role: "rrhh",
  isSupervisor: true,
  supervisorId: "supervisor-uuid-001",
  isActive: true,
});

// =========================================================================
// LITERAL expected normalized payloads (NOT generated by production code)
// =========================================================================

export const SAMPLE_MINIMAL_NORMALIZED: NormalizedPayload = Object.freeze({
  email: "juan.perez@example.com",
  nombre: "Juan",
  apellido1: "Pérez",
  apellido2: null,
  employeeId: "",
  weeklyHours: 40,
  dni: null,
  telefono: null,
  cargo: null,
  departamento: null,
  empresa: null,
  scheduleId: null,
  calendarId: null,
  fechaInicio: null,
  fechaFin: null,
  role: "employee" as const,
  isSupervisor: false,
  supervisorId: null,
  isActive: true,
  displayName: "Juan Pérez",
});

export const SAMPLE_FULL_NORMALIZED: NormalizedPayload = Object.freeze({
  email: "maria.garcia@example.com",
  nombre: "María",
  apellido1: "García",
  apellido2: "López",
  employeeId: "EMP-001",
  weeklyHours: 35,
  dni: "12345678A",
  telefono: "+34123456789",
  cargo: "Developer",
  departamento: "Engineering",
  empresa: "Test Corp",
  scheduleId: "schedule-001",
  calendarId: "calendar-001",
  fechaInicio: "2025-03-01",
  fechaFin: "2025-12-31",
  role: "rrhh" as const,
  isSupervisor: true,
  supervisorId: "supervisor-uuid-001",
  isActive: true,
  displayName: "María García López",
});

// =========================================================================
// Literal operation IDs and boundaries
// =========================================================================

export const OP_IDS = Object.freeze({
  minimal: "00000000-0000-4000-a000-000000000001",
  full: "00000000-0000-4000-a000-000000000002",
  pending: "00000000-0000-4000-a000-000000000010",
  active: "00000000-0000-4000-a000-000000000020",
  completed: "00000000-0000-4000-a000-000000000030",
  failed: "00000000-0000-4000-a000-000000000040",
  manualRecovery: "00000000-0000-4000-a000-000000000050",
});

export const BOUNDARIES = Object.freeze({
  acquire: "acquire",
  authPreflight: "auth_preflight",
  authCreate: "auth_create",
  profileCommit: "profile_commit",
});

// =========================================================================
// LITERAL precomputed deterministic IDs (NOT generated by production code)
// Computed independently via: node -e "crypto.createHash('sha256').update(input).digest('hex')"
// =========================================================================

/** dispatchId(OP_IDS.minimal, "acquire", 0, 0) */
export const FIXTURE_DISPATCH_ID = "d8c2bea7bd64e52bc0bd069d10127d36a9fc4b3df7b77c1b875d368bf3f4419f";

/** auditEventId(OP_IDS.minimal, "authorization", "denial", 0, 0) */
export const FIXTURE_AUDIT_ID = "cb11ae62d9838d2101d7568d53eebd97749fb25af85b59df889ee1a241d9730a";

/** ownerToken(FIXTURE_DISPATCH_ID, 0) */
export const FIXTURE_OWNER_TOKEN = "f7d1a9d3123a9f917a277f1e02f32131e88367d9d55d99b7e9800ece083ba07e";

/** fingerprintPayload(SAMPLE_MINIMAL_PAYLOAD) — canonical all-keys SHA-256 */
export const FIXTURE_FINGERPRINT_MINIMAL = "5adb42d0a7b58690da0fd3b99151a2912d1a47b76248c8d9caa83fabc1365b52";

/** deriveDisplayName("Juan", "Pérez") */
export const FIXTURE_DISPLAY_NAME_MINIMAL = "Juan Pérez";

// =========================================================================
// Integrity checks: literal values MUST equal production output
// If production drifts, these assertions fail — the fixtures are the source of truth.
// =========================================================================

import { strict as assert } from "node:assert";

// Valid-pair conformance
for (const pair of CANONICAL_VALID_PAIRS) {
  assert.strictEqual(
    isValidStatusPhasePair(pair.status, pair.phase),
    true,
    `fixture pair (${pair.status}, ${pair.phase}) must be valid`,
  );
}

// Terminal statuses pair only with "terminal"
for (const ts of TERMINAL_STATUSES) {
  assert.deepStrictEqual(
    VALID_STATUS_PHASE_PAIRS[ts],
    ["terminal"] as readonly ProvisioningPhase[],
  );
}

// Normalization: production MUST equal literal
const normMin = normalizePayload({ ...SAMPLE_MINIMAL_PAYLOAD });
assert.deepStrictEqual(normMin, SAMPLE_MINIMAL_NORMALIZED, "minimal normalized payload mismatch");

const normFull = normalizePayload({ ...SAMPLE_FULL_PAYLOAD });
assert.deepStrictEqual(normFull, SAMPLE_FULL_NORMALIZED, "full normalized payload mismatch");

// Fingerprint: production MUST equal literal
const fpLiteral = fingerprintPayload({ ...SAMPLE_MINIMAL_PAYLOAD });
assert.strictEqual(fpLiteral, FIXTURE_FINGERPRINT_MINIMAL, "fingerprint mismatch");

// IDs: production MUST equal literal
assert.strictEqual(
  deriveDispatchId(OP_IDS.minimal, BOUNDARIES.acquire, 0, 0),
  FIXTURE_DISPATCH_ID,
  "dispatchId mismatch",
);
assert.strictEqual(
  deriveAuditEventId(OP_IDS.minimal, "authorization", "denial", 0, 0),
  FIXTURE_AUDIT_ID,
  "auditEventId mismatch",
);
assert.strictEqual(
  deriveOwnerToken(FIXTURE_DISPATCH_ID, 0),
  FIXTURE_OWNER_TOKEN,
  "ownerToken mismatch",
);

// Display name
assert.strictEqual(
  deriveDisplayName("Juan", "Pérez"),
  FIXTURE_DISPLAY_NAME_MINIMAL,
  "displayName mismatch",
);

// Format validation
for (const id of [FIXTURE_DISPATCH_ID, FIXTURE_AUDIT_ID, FIXTURE_OWNER_TOKEN, FIXTURE_FINGERPRINT_MINIMAL]) {
  assert.strictEqual(id.length, 64, `id length != 64: ${id}`);
  assert.ok(/^[0-9a-f]{64}$/.test(id), `not lower-case hex: ${id}`);
}

// --- Recursive immutability proof -----------------------------------------
// Every exported fixture value MUST be deep-frozen — Object.isFrozen at
// every nesting level, and property assignment MUST throw (silent failure
// in sloppy mode, TypeError in strict mode).

function assertDeepFrozen(value: unknown, path: string): void {
  if (value === null || value === undefined) return;
  if (typeof value !== "object") return;

  assert.ok(
    Object.isFrozen(value),
    `${path} must be frozen`,
  );

  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) {
      assertDeepFrozen(value[i], `${path}[${i}]`);
    }
  } else {
    for (const key of Object.keys(value as Record<string, unknown>)) {
      assertDeepFrozen((value as Record<string, unknown>)[key], `${path}.${key}`);
    }
  }
}

// Mutation must be rejected (strict-mode throws TypeError).
function assertMutationRejected(target: Record<string, unknown>, key: string, label: string): void {
  assert.throws(
    () => { target[key] = "mutated"; },
    /TypeError|Cannot assign/,
    `${label}: mutation must be rejected`,
  );
}

// Top-level exported fixture objects
assertDeepFrozen(CANONICAL_VALID_PAIRS, "CANONICAL_VALID_PAIRS");
for (let i = 0; i < CANONICAL_VALID_PAIRS.length; i++) {
  assertDeepFrozen(CANONICAL_VALID_PAIRS[i], `CANONICAL_VALID_PAIRS[${i}]`);
}
assertDeepFrozen(TERMINAL_STATUSES, "TERMINAL_STATUSES");
assertDeepFrozen(NON_TERMINAL_STATUSES, "NON_TERMINAL_STATUSES");
assertDeepFrozen(SAMPLE_MINIMAL_PAYLOAD, "SAMPLE_MINIMAL_PAYLOAD");
assertDeepFrozen(SAMPLE_FULL_PAYLOAD, "SAMPLE_FULL_PAYLOAD");
assertDeepFrozen(SAMPLE_MINIMAL_NORMALIZED, "SAMPLE_MINIMAL_NORMALIZED");
assertDeepFrozen(SAMPLE_FULL_NORMALIZED, "SAMPLE_FULL_NORMALIZED");
assertDeepFrozen(OP_IDS, "OP_IDS");
assertDeepFrozen(BOUNDARIES, "BOUNDARIES");

// Mutation rejection: try to overwrite a property on a frozen fixture
assertMutationRejected(SAMPLE_MINIMAL_NORMALIZED as unknown as Record<string, unknown>, "email", "SAMPLE_MINIMAL_NORMALIZED.email");
assertMutationRejected(SAMPLE_FULL_NORMALIZED as unknown as Record<string, unknown>, "weeklyHours", "SAMPLE_FULL_NORMALIZED.weeklyHours");
assertMutationRejected(OP_IDS as unknown as Record<string, unknown>, "minimal", "OP_IDS.minimal");
assertMutationRejected(CANONICAL_VALID_PAIRS as unknown as Record<string, unknown>, "0", "CANONICAL_VALID_PAIRS[0]");

console.log("OK: fixtures integrity checks passed");

// Immutability proof: all exported fixture structures are deep-frozen
console.log("OK: fixture immutability proof passed (all exports recursively frozen, mutation rejected)");
